import Navbar from "@/components/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Tajawal } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Tajawal({ subsets: ["latin"], weight: ["300", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="ar" dir="rtl">
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
